modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId= "dttfc" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Dynamic Trees TFC" #mandatory
logoFile="dttfc.png" #optional
authors="EERussianguy" #optional
description='''
An addon for TFC and Dynamic Trees.
'''
[[dependencies.dttfc]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.dttfc]] #optional
    modId="tfc" #mandatory
    mandatory=true #mandatory
    versionRange="[0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dttfc]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dttfc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
