cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/acacia.txt >>acacia.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/birch.txt >>ash.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/birch.txt >>aspen.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/birch.txt >>birch.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/darkoak.txt >>blackwood.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/darkoak.txt >>chestnut.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/spruce.txt >>douglas_fir.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/darkoak.txt >>hickory.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/jungle.txt >>kapok.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/oak.txt >>maple.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/oak.txt >>oak.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/jungle.txt >>palm.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/spruce.txt >>pine.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/darkoak.txt >>rosewood.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/megaspruce.txt >>sequoia.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/spruce.txt >>spruce.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/spruce.txt >>sycamore.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/spruce.txt >>white_cedar.txt
cat ~/workspace/DynamicTrees/src/main/resources/assets/dynamictrees/trees/birch.txt >>willow.txt
