modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Gaelmare/dynamictreestfc/issues"

[[mods]]
modId = "dttfc"
version = "${mod_version}"
displayName = "Dynamic Trees TFC"
logoFile = "dttfc.png"
authors = "Gaelmare and EERussianguy (Ported the mod to version NeoForge 1.21.1 XaramirV)"
description = '''
An addon for TFC and Dynamic Trees.
'''

[[dependencies.dttfc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.234,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dttfc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.dttfc]]
modId = "dynamictrees"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dttfc]]
modId = "tfc"
type = "required"
versionRange = "[4.1.2,)"
ordering = "AFTER"
side = "BOTH"
